server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/aO5iFGTCVl
    username: aO5iFGTCVl
    password: jIYyfdKonj
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect